import type { Metadata } from "next";
import "./globals.css";
import "./responsive.css";
import Header from "../components/layout/Header";
import Footer from "../components/layout/Footer";
import ScrollToTopButton from "../components/layout/ScrollToTopButton";
import { montserrat } from "../fonts/font";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={montserrat.className}>
                <Header />
                <main>
                    {children}
                </main>
                <Footer />
                <ScrollToTopButton />
            </body>
        </html>
    );
}